### ISSUE TITLE
[Bug]: Crash on Multiplayer Server

### ISSUE THREAD

**Issue by spoorn** [samedifferent/Ecologics#36]
### Mod Version

1.5.3

### Mod Loader

Fabric

### Mod Loader Version

0.13.3

### What happened?

Crashes when trying to start server

### latest.log

```
[17:43:24] [main/WARN]: Error loading class: samebutdifferent/ecologics/util/SignTypeHelper (java.lang.RuntimeException: Cannot load class samebutdifferent.ecologics.util.SignTypeHelper in environment type SERVER)
[17:43:24] [main/WARN]: Error loading class: samebutdifferent/ecologics/util/SignTypeHelper (java.lang.RuntimeException: Cannot load class samebutdifferent.ecologics.util.SignTypeHelper in environment type SERVER)
[17:43:24] [main/WARN]: Error loading class: samebutdifferent/ecologics/util/SignTypeHelper (java.lang.RuntimeException: Cannot load class samebutdifferent.ecologics.util.SignTypeHelper in environment type SERVER)
[17:43:24] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: Cannot load class samebutdifferent.ecologics.util.SignTypeHelper in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:33) ~[server-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:19) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:86) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:85) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:291) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 7 more
```

**Comment by dopadream** [comment]
I'm terribly sorry for this, it was a complete oversight on my end. It should be fixed now.
